import CollapsiblePanel from '../common/CollapsiblePanel'

interface Props {
  content: string
}

export default function CoverLetterPanel({ content }: Props) {
  const lines = content.split('\n')

  const paragraphs: { type: 'blank' | 'text'; value: string }[] = []
  let buffer: string[] = []

  for (const line of lines) {
    if (line.trim() === '') {
      if (buffer.length) {
        paragraphs.push({ type: 'text', value: buffer.join('\n') })
        buffer = []
      }
      paragraphs.push({ type: 'blank', value: '' })
    } else {
      buffer.push(line)
    }
  }
  if (buffer.length) paragraphs.push({ type: 'text', value: buffer.join('\n') })

  return (
    <CollapsiblePanel title="Cover Letter" defaultOpen={false}>
      {/* Letter paper */}
      <div className="flex justify-center py-2">
        <div
          className="w-full max-w-2xl rounded-xl shadow-lg overflow-hidden"
          style={{ background: '#ffffff', border: '1px solid #e2e8f0' }}
        >
          {/* Letter header bar */}
          <div
            className="px-10 py-4 flex items-center gap-3"
            style={{ background: 'linear-gradient(to right, #6366f1, #3b82f6)' }}
          >
            <svg className="w-5 h-5 text-white flex-shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
            </svg>
            <span className="text-white text-sm font-semibold tracking-wide uppercase">Cover Letter</span>
          </div>

          {/* Letter body */}
          <div className="px-10 py-8">
            {paragraphs.map((block, i) => {
              if (block.type === 'blank') return <div key={i} className="h-4" />

              const text = block.value
              const isSubjectLine = /^subject\s*:/i.test(text.trim())
              const isDearLine = /^dear\s/i.test(text.trim())
              const isClosing = /^(sincerely|regards|best regards|yours truly|respectfully)/i.test(text.trim())

              if (isSubjectLine) {
                return (
                  <p key={i} className="text-sm font-semibold mb-3" style={{ color: '#1e293b' }}>
                    {text}
                  </p>
                )
              }

              if (isDearLine) {
                return (
                  <p key={i} className="text-sm font-medium mb-4" style={{ color: '#1e293b' }}>
                    {text}
                  </p>
                )
              }

              if (isClosing) {
                return (
                  <p key={i} className="text-sm mt-6" style={{ color: '#334155', whiteSpace: 'pre-wrap' }}>
                    {text}
                  </p>
                )
              }

              return (
                <p key={i} className="text-sm leading-relaxed" style={{ color: '#334155', whiteSpace: 'pre-wrap' }}>
                  {text}
                </p>
              )
            })}
          </div>

          {/* Footer */}
          <div className="px-10 py-3 flex items-center justify-between" style={{ background: '#f8fafc', borderTop: '1px solid #e2e8f0' }}>
            <span className="text-xs" style={{ color: '#94a3b8' }}>Generated by TailorIQ</span>
            <span className="text-xs font-medium" style={{ color: '#6366f1' }}>AI-Tailored</span>
          </div>
        </div>
      </div>
    </CollapsiblePanel>
  )
}
