export interface TemplateDefinition {
  id: string
  name: string
  description: string
  accentColor: string      // CSS color for the card indicator stripe
  headerBg: string | null  // header band color (null = plain)
  headingColor: string     // section heading color
  fontHint: string         // shown as tag on card
  layout: 'single' | 'two-column'
}

export const TEMPLATES: TemplateDefinition[] = [
  {
    id: 'ats_classic',
    name: 'ATS Classic',
    description: 'Clean single-column, ATS-safe',
    accentColor: '#1a1a1a',
    headerBg: null,
    headingColor: '#000000',
    fontHint: 'Calibri',
    layout: 'single',
  },
  {
    id: 'microsoft_modern',
    name: 'Microsoft Modern',
    description: 'Navy header band, Word 2024 style',
    accentColor: '#2b579a',
    headerBg: '#2b579a',
    headingColor: '#2b579a',
    fontHint: 'Calibri',
    layout: 'single',
  },
  {
    id: 'corporate_blue',
    name: 'Corporate Blue',
    description: 'Navy gradient rule, boardroom formal',
    accentColor: '#1a3a5c',
    headerBg: null,
    headingColor: '#1a3a5c',
    fontHint: 'Segoe UI',
    layout: 'single',
  },
  {
    id: 'executive_dark',
    name: 'Executive Dark',
    description: 'Dark sidebar, indigo accent lines',
    accentColor: '#6366f1',
    headerBg: '#1a1a2e',
    headingColor: '#6366f1',
    fontHint: 'Calibri',
    layout: 'two-column',
  },
  {
    id: 'clean_minimal',
    name: 'Clean Minimal',
    description: 'Ultra-whitespace, Swiss modern',
    accentColor: '#999999',
    headerBg: null,
    headingColor: '#888888',
    fontHint: 'Helvetica',
    layout: 'single',
  },
  {
    id: 'charcoal_gold',
    name: 'Charcoal Gold',
    description: 'Dark header, gold accent — executive',
    accentColor: '#c9a84c',
    headerBg: '#1e2a3a',
    headingColor: '#1e2a3a',
    fontHint: 'Calibri',
    layout: 'single',
  },
  {
    id: 'elegant_serif',
    name: 'Elegant Serif',
    description: 'Georgia serif, warm classic luxury',
    accentColor: '#c4956a',
    headerBg: null,
    headingColor: '#2c1810',
    fontHint: 'Georgia',
    layout: 'single',
  },
  {
    id: 'tech_pro',
    name: 'Tech Pro',
    description: 'Dark terminal, developer aesthetic',
    accentColor: '#79c0ff',
    headerBg: '#0d1117',
    headingColor: '#79c0ff',
    fontHint: 'Monospace',
    layout: 'single',
  },
  {
    id: 'creative_teal',
    name: 'Creative Teal',
    description: 'Teal-to-cyan gradient header',
    accentColor: '#0d9488',
    headerBg: '#0d9488',
    headingColor: '#0d9488',
    fontHint: 'Calibri',
    layout: 'single',
  },
  {
    id: 'linkedin_style',
    name: 'LinkedIn Style',
    description: 'LinkedIn PDF export look',
    accentColor: '#0077b5',
    headerBg: null,
    headingColor: '#0077b5',
    fontHint: 'Calibri',
    layout: 'single',
  },
  {
    id: 'harvard_classic',
    name: 'Harvard Classic',
    description: 'Traditional Times serif, academia',
    accentColor: '#a51c30',
    headerBg: null,
    headingColor: '#a51c30',
    fontHint: 'Times New Roman',
    layout: 'single',
  },
  {
    id: 'compact_dense',
    name: 'Compact Dense',
    description: 'Maximum content, minimal whitespace',
    accentColor: '#334155',
    headerBg: null,
    headingColor: '#334155',
    fontHint: 'Arial',
    layout: 'single',
  },
  {
    id: 'two_column_split',
    name: 'Two Column',
    description: 'Skill bars left, experience right',
    accentColor: '#1e3a5f',
    headerBg: '#1e3a5f',
    headingColor: '#1e3a5f',
    fontHint: 'Calibri',
    layout: 'two-column',
  },
  {
    id: 'green_professional',
    name: 'Green Professional',
    description: 'Forest green accent, clean authority',
    accentColor: '#16a34a',
    headerBg: null,
    headingColor: '#14532d',
    fontHint: 'Calibri',
    layout: 'single',
  },
  {
    id: 'purple_modern',
    name: 'Purple Modern',
    description: 'Deep purple gradient, premium',
    accentColor: '#7c3aed',
    headerBg: '#4c1d95',
    headingColor: '#6d28d9',
    fontHint: 'Calibri',
    layout: 'single',
  },
]
